version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stack-daniel"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-j1f6ghktzn15"
s3_prefix = "stack-daniel"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
